In [1]:
# load env
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
# import SchemaMapEngine for testing the output
import sys
sys.path.append(".")

from src.models.schema_mapper.engine import SchemaMapEngine

/opt/anaconda3/lib/python3.13/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

/Users/sanskarpandey1606/Desktop/MetaHarmonizer_App/backend/engine

In [3]:
# now generate the output using prebuild model and check he mappers effeciency
engine = SchemaMapEngine(
    clinical_data_path="../../metadata_samples/new_meta.csv",
    mode="manual"
)

dff_out = engine.run_schema_mapping()

dff_out.head()

24/03/2026 03:11:23 PM - WARNING - DefaultLogger: [NoMatch] 'antibiotics_current_use' did not match any stage
24/03/2026 03:11:31 PM - WARNING - DefaultLogger: [NoMatch] 'non_westernized' did not match any stage
24/03/2026 03:11:32 PM - WARNING - DefaultLogger: [NoMatch] 'sequencing_platform' did not match any stage
24/03/2026 03:11:34 PM - WARNING - DefaultLogger: [NoMatch] 'DNA_extraction_kit' did not match any stage
24/03/2026 03:11:34 PM - WARNING - DefaultLogger: [NoMatch] 'PMID' did not match any stage
24/03/2026 03:11:35 PM - WARNING - DefaultLogger: [NoMatch] 'number_reads' did not match any stage
24/03/2026 03:11:35 PM - WARNING - DefaultLogger: [NoMatch] 'number_bases' did not match any stage
24/03/2026 03:11:35 PM - WARNING - DefaultLogger: [NoMatch] 'minimum_read_length' did not match any stage
24/03/2026 03:11:35 PM - WARNING - DefaultLogger: [NoMatch] 'median_read_length' did not match any stage
24/03/2026 03:11:35 PM - WARNING - DefaultLogger: [NoMatch] 'NCBI_accession' did not match any stage
24/03/2026 03:11:36 PM - WARNING - DefaultLogger: [NoMatch] 'pregnant' did not match any stage
24/03/2026 03:11:38 PM - WARNING - DefaultLogger: [NoMatch] 'lactating' did not match any stage
24/03/2026 03:11:41 PM - WARNING - DefaultLogger: [NoMatch] 'curator' did not match any stage
24/03/2026 03:11:41 PM - WARNING - DefaultLogger: [NoMatch] 'BMI' did not match any stage
24/03/2026 03:11:45 PM - WARNING - DefaultLogger: [NoMatch] 'family_role' did not match any stage
24/03/2026 03:11:48 PM - WARNING - DefaultLogger: [NoMatch] 'born_method' did not match any stage
24/03/2026 03:11:49 PM - WARNING - DefaultLogger: [NoMatch] 'feeding_practice' did not match any stage
24/03/2026 03:11:51 PM - WARNING - DefaultLogger: [NoMatch] 'diet' did not match any stage
24/03/2026 03:11:53 PM - WARNING - DefaultLogger: [NoMatch] 'visit_number' did not match any stage
24/03/2026 03:11:54 PM - WARNING - DefaultLogger: [NoMatch] 'premature' did not match any stage
24/03/2026 03:11:54 PM - WARNING - DefaultLogger: [NoMatch] 'birth_weight' did not match any stage
24/03/2026 03:11:55 PM - WARNING - DefaultLogger: [NoMatch] 'antibiotics_family' did not match any stage
24/03/2026 03:12:01 PM - WARNING - DefaultLogger: [NoMatch] 'creatine' did not match any stage
24/03/2026 03:12:01 PM - WARNING - DefaultLogger: [NoMatch] 'albumine' did not match any stage
24/03/2026 03:12:03 PM - WARNING - DefaultLogger: [NoMatch] 'hscrp' did not match any stage
24/03/2026 03:12:05 PM - WARNING - DefaultLogger: [NoMatch] 'ESR' did not match any stage
24/03/2026 03:12:07 PM - WARNING - DefaultLogger: [NoMatch] 'alt' did not match any stage
24/03/2026 03:12:09 PM - WARNING - DefaultLogger: [NoMatch] 'globulin' did not match any stage
24/03/2026 03:12:11 PM - WARNING - DefaultLogger: [NoMatch] 'urea_nitrogen' did not match any stage
24/03/2026 03:12:13 PM - WARNING - DefaultLogger: [NoMatch] 'BASDAI' did not match any stage
24/03/2026 03:12:13 PM - WARNING - DefaultLogger: [NoMatch] 'BASFI' did not match any stage
24/03/2026 03:12:14 PM - WARNING - DefaultLogger: [NoMatch] 'flg_genotype' did not match any stage
24/03/2026 03:12:16 PM - WARNING - DefaultLogger: [NoMatch] 'menopausal_status' did not match any stage
24/03/2026 03:12:18 PM - WARNING - DefaultLogger: [NoMatch] 'uncurated_metadata' did not match any stage
24/03/2026 03:12:21 PM - WARNING - DefaultLogger: [NoMatch] 'triglycerides' did not match any stage
24/03/2026 03:12:22 PM - WARNING - DefaultLogger: [NoMatch] 'hdl' did not match any stage
24/03/2026 03:12:24 PM - WARNING - DefaultLogger: [NoMatch] 'ldl' did not match any stage
24/03/2026 03:12:26 PM - WARNING - DefaultLogger: [NoMatch] 'hba1c' did not match any stage
24/03/2026 03:12:28 PM - WARNING - DefaultLogger: [NoMatch] 'RECIST' did not match any stage
24/03/2026 03:12:29 PM - WARNING - DefaultLogger: [NoMatch] 'ORR' did not match any stage
24/03/2026 03:12:30 PM - WARNING - DefaultLogger: [NoMatch] 'smoker' did not match any stage
24/03/2026 03:12:31 PM - WARNING - DefaultLogger: [NoMatch] 'ever_smoker' did not match any stage
24/03/2026 03:12:32 PM - WARNING - DefaultLogger: [NoMatch] 'history_of_periodontitis' did not match any stage
24/03/2026 03:12:32 PM - WARNING - DefaultLogger: [NoMatch] 'PPD_M' did not match any stage
24/03/2026 03:12:32 PM - WARNING - DefaultLogger: [NoMatch] 'PPD_B' did not match any stage
24/03/2026 03:12:33 PM - WARNING - DefaultLogger: [NoMatch] 'PPD_L' did not match any stage
24/03/2026 03:12:36 PM - WARNING - DefaultLogger: [NoMatch] 'fobt' did not match any stage
24/03/2026 03:12:38 PM - WARNING - DefaultLogger: [NoMatch] 'calprotectin' did not match any stage
24/03/2026 03:12:39 PM - WARNING - DefaultLogger: [NoMatch] 'HBI' did not match any stage
24/03/2026 03:12:40 PM - WARNING - DefaultLogger: [NoMatch] 'SCCAI' did not match any stage
24/03/2026 03:12:41 PM - WARNING - DefaultLogger: [NoMatch] 'mumps' did not match any stage
24/03/2026 03:12:44 PM - WARNING - DefaultLogger: [NoMatch] 'cholesterol' did not match any stage
24/03/2026 03:12:46 PM - WARNING - DefaultLogger: [NoMatch] 'c_peptide' did not match any stage
24/03/2026 03:12:48 PM - WARNING - DefaultLogger: [NoMatch] 'glucose' did not match any stage
24/03/2026 03:12:50 PM - WARNING - DefaultLogger: [NoMatch] 'creatinine' did not match any stage
24/03/2026 03:12:50 PM - WARNING - DefaultLogger: [NoMatch] 'bilubirin' did not match any stage
24/03/2026 03:12:53 PM - WARNING - DefaultLogger: [NoMatch] 'prothrombin_time' did not match any stage
24/03/2026 03:12:54 PM - WARNING - DefaultLogger: [NoMatch] 'hemoglobinometry' did not match any stage
24/03/2026 03:12:54 PM - WARNING - DefaultLogger: [NoMatch] 'FMT_role' did not match any stage
24/03/2026 03:12:57 PM - WARNING - DefaultLogger: [NoMatch] 'dyastolic_p' did not match any stage
24/03/2026 03:12:57 PM - WARNING - DefaultLogger: [NoMatch] 'systolic_p' did not match any stage
24/03/2026 03:12:58 PM - WARNING - DefaultLogger: [NoMatch] 'insulin_cat' did not match any stage
24/03/2026 03:13:00 PM - WARNING - DefaultLogger: [NoMatch] 'adiponectin' did not match any stage
24/03/2026 03:13:02 PM - WARNING - DefaultLogger: [NoMatch] 'glp_1' did not match any stage
24/03/2026 03:13:03 PM - WARNING - DefaultLogger: [NoMatch] 'cd163' did not match any stage
24/03/2026 03:13:06 PM - WARNING - DefaultLogger: [NoMatch] 'leptin' did not match any stage
24/03/2026 03:13:08 PM - WARNING - DefaultLogger: [NoMatch] 'fgf_19' did not match any stage
24/03/2026 03:13:08 PM - WARNING - DefaultLogger: [NoMatch] 'glutamate_decarboxylase_2_antibody' did not match any stage
24/03/2026 03:13:10 PM - WARNING - DefaultLogger: [NoMatch] 'HLA' did not match any stage
24/03/2026 03:13:10 PM - WARNING - DefaultLogger: [NoMatch] 'autoantibody_positive' did not match any stage
24/03/2026 03:13:11 PM - WARNING - DefaultLogger: [NoMatch] 'hitchip_probe_class' did not match any stage
24/03/2026 03:13:14 PM - WARNING - DefaultLogger: [NoMatch] 'performance_status' did not match any stage
24/03/2026 03:13:15 PM - WARNING - DefaultLogger: [NoMatch] 'toxicity_above_zero' did not match any stage
24/03/2026 03:13:15 PM - WARNING - DefaultLogger: [NoMatch] 'PFS12' did not match any stage
24/03/2026 03:13:16 PM - WARNING - DefaultLogger: [NoMatch] 'fasting_insulin' did not match any stage
24/03/2026 03:13:16 PM - WARNING - DefaultLogger: [NoMatch] 'fasting_glucose' did not match any stage
24/03/2026 03:13:16 PM - WARNING - DefaultLogger: [NoMatch] 'protein_intake' did not match any stage
24/03/2026 03:13:17 PM - WARNING - DefaultLogger: [NoMatch] 'stec_count' did not match any stage
24/03/2026 03:13:17 PM - WARNING - DefaultLogger: [NoMatch] 'shigatoxin_2_elisa' did not match any stage
24/03/2026 03:13:18 PM - WARNING - DefaultLogger: [NoMatch] 'stool_texture' did not match any stage
24/03/2026 03:13:18 PM - WARNING - DefaultLogger: [NoMatch] 'anti_PD_1' did not match any stage
24/03/2026 03:13:20 PM - WARNING - DefaultLogger: [NoMatch] 'bristol_score' did not match any stage
24/03/2026 03:13:20 PM - WARNING - DefaultLogger: [NoMatch] 'hsCRP' did not match any stage
24/03/2026 03:13:20 PM - WARNING - DefaultLogger: [NoMatch] 'LDL' did not match any stage
24/03/2026 03:13:21 PM - WARNING - DefaultLogger: [NoMatch] 'mgs_richness' did not match any stage
24/03/2026 03:13:21 PM - WARNING - DefaultLogger: [NoMatch] 'ferm_milk_prod_consumer' did not match any stage
24/03/2026 03:13:22 PM - WARNING - DefaultLogger: [NoMatch] 'inr' did not match any stage
24/03/2026 03:13:23 PM - WARNING - DefaultLogger: [NoMatch] 'birth_control_pil' did not match any stage
24/03/2026 03:13:23 PM - WARNING - DefaultLogger: [NoMatch] 'c_section_type' did not match any stage
24/03/2026 03:13:23 PM - WARNING - DefaultLogger: [NoMatch] 'hla_drb12' did not match any stage
24/03/2026 03:13:24 PM - WARNING - DefaultLogger: [NoMatch] 'hla_dqa12' did not match any stage
24/03/2026 03:13:24 PM - WARNING - DefaultLogger: [NoMatch] 'hla_dqa11' did not match any stage
24/03/2026 03:13:24 PM - WARNING - DefaultLogger: [NoMatch] 'hla_drb11' did not match any stage
24/03/2026 03:13:25 PM - WARNING - DefaultLogger: [NoMatch] 'zigosity' did not match any stage
24/03/2026 03:13:25 PM - WARNING - DefaultLogger: [NoMatch] 'brinkman_index' did not match any stage
24/03/2026 03:13:25 PM - WARNING - DefaultLogger: [NoMatch] 'alcohol_numeric' did not match any stage
24/03/2026 03:13:25 PM - WARNING - DefaultLogger: [NoMatch] 'ALT' did not match any stage
24/03/2026 03:13:27 PM - WARNING - DefaultLogger: [NoMatch] 'eGFR' did not match any stage

,query,stage,method,match1,match1_score,match1_source,match2,match2_score,match2_source,match3,match3_score,match3_source,match4,match4_score,match4_source,match5,match5_score,match5_source
0,study_name,stage3,semantic,study_design,0.7538,study type,treatment_group,0.7475,study group,location,0.6754,study site,specimen_type,0.3973,specimen type,specimen_type_ontology_term_id,0.3650,
1,sample_id,invalid,id_column,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,subject_id,invalid,id_column,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,body_site,stage1,std_exact,body_site,1.0000,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,study_condition,stage3,semantic,study_design,0.7099,,treatment_group,0.6442,study group,location,0.5853,study site,disease,0.5452,condition,target_condition,0.3949,primary condition

In [5]:
import os 
print (os.getcwd())

/Users/sanskarpandey1606/Desktop/MetaHarmonizer_App/backend/engine

In [6]:
import os
print(os.listdir())

['anaconda_projects', 'Test_engine.ipynb', 'out.log', '.virtual_documents', '.ipynb_checkpoints', 'data', 'src']

In [7]:
print(os.listdir(".."))

['test_engine.py', 'app', 'requirements.txt', 'venv', 'data', 'engine']

In [8]:
print(os.listdir("../.."))

['metadata_samples', '.DS_Store', 'frontend', 'anaconda_projects', 'Untitled.ipynb', 'pics', 'backend', 'README.md', '.gitignore', 'out.log', '.env', '.virtual_documents', '.ipynb_checkpoints', '.git', 'data']

In [9]:
print(os.listdir("../../metadata_samples"))

['curated_meta.csv', 'new_meta.csv']

In [ ]:
import os
print("os.getenv("GEMINI_API_KEY"))

In [4]:
dff_out.head()

,query,stage,method,match1,match1_score,match1_source,match2,match2_score,match2_source,match3,match3_score,match3_source,match4,match4_score,match4_source,match5,match5_score,match5_source
0,study_name,stage3,semantic,study_design,0.7538,study type,treatment_group,0.7475,study group,location,0.6754,study site,specimen_type,0.3973,specimen type,specimen_type_ontology_term_id,0.3650,
1,sample_id,invalid,id_column,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,subject_id,invalid,id_column,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,body_site,stage1,std_exact,body_site,1.0000,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,study_condition,stage3,semantic,study_design,0.7099,,treatment_group,0.6442,study group,location,0.5853,study site,disease,0.5452,condition,target_condition,0.3949,primary condition

In [6]:
# now load the genearted output and compare with the previous
import pandas as pd

new_meta = pd.read_csv("../../metadata_samples/new_meta.csv")
curated = pd.read_csv("../../metadata_samples/curated_meta.csv")
output = pd.read_csv("data/schema_mapping_eval/new_meta_manual.csv")

print(new_meta.shape)
print(curated.shape)
print(output.shape)

(707, 141)
(21881, 37)
(43, 18)

/var/folders/07/n3fbcfx95z54qfj14n4hyzsw0000gn/T/ipykernel_6281/2258378987.py:4: DtypeWarning: Columns (13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  curated = pd.read_csv("../../metadata_samples/curated_meta.csv")

In [7]:
output.head()

,query,stage,method,match1,match1_score,match1_source,match2,match2_score,match2_source,match3,match3_score,match3_source,match4,match4_score,match4_source,match5,match5_score,match5_source
0,study_name,stage3,semantic,study_design,0.7538,study type,treatment_group,0.7475,study group,location,0.6754,study site,specimen_type,0.3973,specimen type,specimen_type_ontology_term_id,0.3650,NaN
1,sample_id,invalid,id_column,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,subject_id,invalid,id_column,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,body_site,stage1,std_exact,body_site,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,study_condition,stage3,semantic,study_design,0.7099,NaN,treatment_group,0.6442,study group,location,0.5853,study site,disease,0.5452,condition,target_condition,0.3949,primary condition

In [9]:
output.columns

Index(['query', 'stage', 'method', 'match1', 'match1_score', 'match1_source',
       'match2', 'match2_score', 'match2_source', 'match3', 'match3_score',
       'match3_source', 'match4', 'match4_score', 'match4_source', 'match5',
       'match5_score', 'match5_source'],
      dtype='object')

In [10]:
# Stage Distribution
output["stage"].value_counts()

stage
stage3     23
stage1      8
invalid     6
stage2      6
Name: count, dtype: int64

In [12]:
# confidence anlaysis

output["match1_score"].describe()

count    37.000000
mean      0.688989
std       0.236018
min       0.300000
25%       0.521000
50%       0.654700
75%       1.000000
max       1.000000
Name: match1_score, dtype: float64

In [13]:
# Average confidence
output["match1_score"].mean()

0.6889891891891892

In [15]:
# checking the output
total_cols = len(new_meta.columns)
matched_cols = len(output)

print("Total columns:", total_cols)
print("Matched columns", matched_cols)
print("Unmatched:", total_cols - matched_cols)

Total columns: 141
Matched columns 43
Unmatched: 98

In [17]:
# check the unmatched columns
all_cols = list(new_meta.columns)
matched_cols = list(output["query"])

unmatched = [c for c in all_cols if c not in matched_cols]

len(unmatched), unmatched[:20]

(98,
 ['antibiotics_current_use',
  'non_westernized',
  'sequencing_platform',
  'DNA_extraction_kit',
  'PMID',
  'number_reads',
  'number_bases',
  'minimum_read_length',
  'median_read_length',
  'NCBI_accession',
  'pregnant',
  'lactating',
  'curator',
  'BMI',
  'family_role',
  'born_method',
  'feeding_practice',
  'diet',
  'visit_number',
  'premature'])

In [18]:
# Check stage quality
output[["query", "stage", "match1", "match1_score"]].head(20)

                         query    stage            match1  match1_score
0                   study_name   stage3      study_design        0.7538
1                    sample_id  invalid               NaN           NaN
2                   subject_id  invalid               NaN           NaN
3                    body_site   stage1         body_site        1.0000
4              study_condition   stage3      study_design        0.7099
5                      disease   stage1           disease        1.0000
6                          age   stage1  age_at_diagnosis        1.0000
7                   infant_age   stage3  age_at_diagnosis        0.8333
8                 age_category   stage1         age_group        1.0000
9                       gender   stage1               sex        1.0000
10                     country   stage1           country        1.0000
11                      family   stage3          ancestry        0.5328
12                   treatment   stage1    treatment_type        1.0000
13  days_from_first_collection   stage3   treatment_start        0.6547
14                    location   stage1          location        1.0000
15          travel_destination   stage3          location        0.5116
16             gestational_age   stage3  age_at_diagnosis        0.6546
17             disease_subtype   stage3    cancer_subtype        0.6823
18            days_after_onset   stage3   treatment_start        0.5036
19                         ast   stage2       cancer_type        0.3000

In [19]:
curated.columns

Index(['study_name', 'sample_id', 'age_years', 'age_min', 'age_max',
       'age_group', 'age_group_ontology_term_id', 'biomarker', 'body_site',
       'body_site_ontology_term_id', 'country', 'country_ontology_term_id',
       'dietary_restriction', 'feces_phenotype_metric',
       'feces_phenotype_value', 'feces_phenotype_metric_ontology_term_id',
       'fmt_role', 'fmt_id', 'sex', 'sex_ontology_term_id', 'hla',
       'hla_ontology_term_id', 'smoker', 'smoker_ontology_term_id', 'control',
       'control_ontology_term_id', 'target_condition',
       'target_condition_ontology_term_id', 'disease',
       'disease_ontology_term_id', 'antibiotics_current_use', 'treatment',
       'treatment_ontology_term_id', 'tumor_staging_ajcc', 'tumor_staging_tnm',
       'unmetadata', 'westernized'],
      dtype='object')

In [20]:
curated.head()

,study_name,sample_id,age_years,age_min,age_max,age_group,age_group_ontology_term_id,biomarker,body_site,body_site_ontology_term_id,...,target_condition_ontology_term_id,disease,disease_ontology_term_id,antibiotics_current_use,treatment,treatment_ontology_term_id,tumor_staging_ajcc,tumor_staging_tnm,unmetadata,westernized
0,AsnicarF_2017,MV_FEI1_t1Q14,0.246575,0.246575,0.246575,Infant,NCIT:C27956,NaN,feces,UBERON:0001988,...,OHMI:0000020,Healthy,NCIT:C115935,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1,AsnicarF_2017,MV_FEI2_t1Q14,0.246575,0.246575,0.246575,Infant,NCIT:C27956,NaN,feces,UBERON:0001988,...,OHMI:0000020,Healthy,NCIT:C115935,NaN,NaN,NaN,NaN,NaN,NaN,Yes
2,AsnicarF_2017,MV_FEI3_t1Q14,0.246575,0.246575,0.246575,Infant,NCIT:C27956,NaN,feces,UBERON:0001988,...,OHMI:0000020,Healthy,NCIT:C115935,NaN,NaN,NaN,NaN,NaN,NaN,Yes
3,AsnicarF_2017,MV_FEI4_t1Q14,1.000000,1.000000,1.000000,Infant,NCIT:C27956,NaN,feces,UBERON:0001988,...,OHMI:0000020,Healthy,NCIT:C115935,NaN,NaN,NaN,NaN,NaN,NaN,Yes
4,AsnicarF_2017,MV_FEI4_t2Q15,1.000000,1.000000,1.000000,Infant,NCIT:C27956,NaN,feces,UBERON:0001988,...,OHMI:0000020,Healthy,NCIT:C115935,NaN,NaN,NaN,NaN,NaN,NaN,Yes

In [22]:
output["stage"].value_counts()
output["match1_score"].mean()
len(unmatched)

98